server:
  port: 8080
spring:
  #*********************************************** Mysql start**********************************************************
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xmbigdata?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "000000"
    initialSize: 20
    minIdle: 50
    maxActive: 500